pass-culture/api-data

.github/workflows/reusable_api_reco_integration_tests.yml
* [Other](?expand=1&template=Refacto_template.md)
=> (BSR) ci: fix api reco integrations tests

.gitignore, apps/recommendation/api/src/huggy/crud/iris.py, apps/recommendation/api/src/huggy/models/iris_france.py, apps/recommendation/api/src/huggy/views/home.py, apps/recommendation/api/src/tests/conftest.py, apps/recommendation/api/src/tests/db/__init__.py, apps/recommendation/api/src/tests/db/iris_france.py, apps/recommendation/api/src/tests/db/schema/iris.py, apps/recommendation/api/src/tests/db_test.py
=> [PC-26673] Switch Iris_France table to mv

.github/workflows/reusable_api_reco_integration_tests.yml, .gitignore, apps/recommendation/api/src/huggy/crud/iris.py, apps/recommendation/api/src/huggy/models/iris_france.py, apps/recommendation/api/src/huggy/utils/env_vars.py, apps/recommendation/api/src/huggy/views/home.py, apps/recommendation/api/src/tests/conftest.py, apps/recommendation/api/src/tests/db/__init__.py, apps/recommendation/api/src/tests/db/iris_france.py, apps/recommendation/api/src/tests/db/schema/iris.py, apps/recommendation/api/src/tests/db_test.py
=> MES v277.0.0

.github/workflows/api_compliance_deploy.yml, .github/workflows/api_reco_deploy.yml
* [Other](?expand=1&template=Refacto_template.md)
=> (BSR) ci: fix slack notification

.github/workflows/api_compliance_deploy.yml
* [Other](?expand=1&template=Refacto_template.md)
=> (BSR) ci: fix slack notification for compliance deploy

apps/fraud/compliance/api/requirements.txt
=> Update compliance API

apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/model_engine/__init__.py, apps/recommendation/api/src/huggy/core/model_engine/recommendation.py, apps/recommendation/api/src/huggy/core/model_engine/similar_offer.py, apps/recommendation/api/src/huggy/models/past_recommended_offers.py, apps/recommendation/api/src/huggy/views/home.py, apps/recommendation/api/src/huggy/views/offer.py
=> #MES 20240529

apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py, apps/recommendation/api/src/huggy/core/model_engine/__init__.py
=> MES #20240539

apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py
=> MES 20240530 #2

apps/fraud/compliance/api/src/pcpapillon/core/offer_categorisation/offer_categorisation_model.py, apps/fraud/compliance/api/src/pcpapillon/utils/configs.py, apps/fraud/compliance/api/src/pcpapillon/utils/data_model.py, apps/fraud/compliance/api/src/pcpapillon/views/offer_categorisation.py
Update the input and output of the offer_categorisation route
https://www.notion.so/passcultureapp/880351701699470cb129e4e0ad6bbcba?v=cfbe4b16778b47218f252bd1b5add4a0&p=83a368f537f746148d25f44e530ed410&pm=s
=> Reafctor / Update input and output of POST /offer_categorisation route

apps/recommendation/api/requirements.txt, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_engine/__init__.py, apps/recommendation/api/src/huggy/core/model_engine/similar_offer.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/configuration.py, apps/recommendation/api/src/huggy/core/scorer/offer.py, apps/recommendation/api/src/huggy/schemas/playlist_params.py, apps/recommendation/api/src/huggy/views/home.py
* [Other](?expand=1&template=Refacto_template.md)
=> (reco) implement semi-edito pl

apps/recommendation/README.md, apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_engine/__init__.py, apps/recommendation/api/src/huggy/core/model_engine/recommendation.py, apps/recommendation/api/src/huggy/core/model_engine/similar_offer.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/configuration.py, apps/recommendation/api/src/huggy/crud/iris.py, apps/recommendation/api/src/huggy/crud/offer.py, apps/recommendation/api/src/huggy/crud/user.py, apps/recommendation/api/src/huggy/models/enriched_user.py, apps/recommendation/api/src/huggy/models/iris_france.py, apps/recommendation/api/src/huggy/models/item_ids.py, apps/recommendation/api/src/huggy/models/past_recommended_offers.py, apps/recommendation/api/src/huggy/models/recommendable_offers_raw.py, apps/recommendation/api/src/huggy/schemas/offer.py, apps/recommendation/api/src/huggy/schemas/playlist_params.py, apps/recommendation/api/src/huggy/schemas/recommendable_offer.py, apps/recommendation/api/src/huggy/schemas/user.py, apps/recommendation/api/src/huggy/utils/mixing.py, apps/recommendation/api/src/huggy/utils/vertex_ai.py, apps/recommendation/api/src/tests/conftest.py, apps/recommendation/api/src/tests/db/models/recommendable_offer_raw.py, apps/recommendation/api/src/tests/db_test.py, apps/recommendation/api/src/tests/unit/crud/iris_test.py
=> (DE-57) doc/write and format docstring for main objects

.github/workflows/api_compliance_deploy.yml
fix CD change paths in github action yaml
=> [DE-340](CI) fix api compliance change paths in CD

apps/recommendation/api/src/huggy/utils/vertex_ai.py
Fix typo which happened during linting of API reco (t.list -> list). All the same kind of modifications have been review manually
No ticket
=> fix: Fix typo (during linting)

apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_ranking.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/configuration.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py
=> (feat): Add recommendation_user_ranking_version_b in endpoint init

apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/offer_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_ranking.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/configuration.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py
=> MES #20240730

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
* [Other](?expand=1&template=Generic_template.md)
=> fix: wrong return within cache for retrieval

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
=> MES #20240730 #2

Makefile, README.md
* [Other](?expand=1&template=Generic_template.md)
=> (fix): Move pre-commit install to new line in install target

apps/recommendation/api/src/huggy/core/model_engine/__init__.py
=> (reco) fix: Include last diversification rank in offer_order

apps/recommendation/api/src/huggy/core/model_selection/endpoint/__init__.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> feat: Add RANKING_VERSION_B_ENPOINT_NAME to allow multiple AB testing

apps/fraud/compliance/api/Dockerfile, apps/fraud/compliance/api/deploy_local.sh
=> feat: Update Dockerfile so that it can run locally

.github/PULL_REQUEST_TEMPLATE/MEP_template.md, .github/PULL_REQUEST_TEMPLATE/MES_template.md, .github/pull_request_template.md
=> doc: Update PR templates

apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/scorer/offer.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> (BSR) feat: add cache to recommendable_offer query

apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/scorer/offer.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> MES #20240830

apps/recommendation/api/src/huggy/core/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/scorer/offer.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> MES #20240905

apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/crud/recommendable_offer.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> MES v20240906

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json
=> MES #20240919v2

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json
=> fix: Update wakeupcall

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json
=> MES #20240919v3

apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py, apps/recommendation/api/src/huggy/core/endpoint/utils.py
=> (reco) feat: add fallback for ranking

apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py, apps/recommendation/api/src/huggy/core/endpoint/utils.py
=> MES #20240924

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json, apps/recommendation/api/src/huggy/core/endpoint/ranking_endpoint.py, apps/recommendation/api/src/huggy/core/endpoint/utils.py
=> MEP #20240924

.github/workflows/sonar_build.yml, sonar-project.properties
=> (DE-239) feat(ci/cd): add sonarcloud analysis to api-data project

.github/workflows/ci_gpt.yml
=> feat: Add gpt4 pr review

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/offer_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/recommendation.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/similar_offer.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py
=> [AB-42](ab-test) Update config for retrieval version b endpoint

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py
Reload model was not working after refacto
Before fix: 
After fix:
=> fix: Fix reload_model_if_newer_is_available not working after refacto

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py
=> MES #20241028v2

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py, apps/fraud/compliance/api/src/pcpapillon/core/offer_categorisation_model.py, apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> fix: Pass model_name as string and Add logging

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py, apps/fraud/compliance/api/src/pcpapillon/core/offer_categorisation_model.py, apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> MES #20241028v3

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py, apps/fraud/compliance/api/src/pcpapillon/core/offer_categorisation_model.py, apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> MEP #20241028v2

apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> refactor: Add model_version loggin

apps/fraud/compliance/api/src/pcpapillon/core/compliance_model.py, apps/fraud/compliance/api/src/pcpapillon/core/offer_categorisation_model.py, apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> MES #20241028v4

apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> (BSR) fix(compliace): Replace rstrip by removesuffix

apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> MES #20241028v5

apps/fraud/compliance/api/src/pcpapillon/utils/model_handler.py
=> MEP #20241028v4

.github/workflows/api_compliance_deploy.yml
=> fix deploy-api-compliance

.github/workflows/api_compliance_deploy.yml
=> MES #20241112v2

apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/offer_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/recommendation.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/similar_offer.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> [reco] add version C mode configuration

.github/workflows/api_reco_deploy.yml
=> fix: Add missing permissions in reco deploy

.github/workflows/api_reco_deploy.yml, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/offer_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/recommendation.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/similar_offer.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> MES #20241113.1

.github/workflows/ci_gpt.yml
=> (BSR) fix(gpt): Fix permissions for gpt review gh yaml

.github/workflows/ci_gpt.yml, apps/fraud/compliance/api/src/pcpapillon/utils/data_model.py, apps/fraud/compliance/api/src/pcpapillon/views/compliance.py
=> MES #20241119

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt
=> (BSR) feat(compliance): Update pyarrow to 18.1.0

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt, apps/fraud/compliance/api/src/pcpapillon/views/home.py
=> (BSR) refactor(compliance): Remove security deprecate routes

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt
Update compliance packages :
* Werkzeug 3.1.3
* nltk 3.9.1
* python-multipart 0.0.17
* gunicorn 23.0.0
=> (BSR) refactor(compliance): Update compliance packages

apps/fraud/compliance/api/Dockerfile, apps/fraud/compliance/api/src/pcpapillon/utils/security.py, apps/recommendation/api/Dockerfile, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/scorer/offer.py, apps/recommendation/api/src/tests/unit/crud/recommendable_offer_test.py, apps/recommendation/db/scripts/create_past_similar_offers.sql
=> (BSR) fix(api): sonarcloud alerts fixes

apps/fraud/compliance/api/Dockerfile
=> (BSR) fix(compliance): Revert Dockerfile Switch to JSON array cmd

apps/elementary/api/src/constants.py, apps/elementary/api/src/utils.py
=> (DE) fix(elementary): handle production project

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/schemas/playlist_params.py, apps/recommendation/api/src/huggy/views/offer.py
=> (DE-1472) feat(reco): Add search_group_names as query param for similar offers

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
=> chore: Fix typo

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/schemas/playlist_params.py, apps/recommendation/api/src/huggy/views/offer.py
=> MES v20250401.0

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt
=> (BSR) chore(package): Update pytorch

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt
=> MEP v20250423

apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/recommendation.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py, apps/recommendation/api/src/huggy/utils/env_vars.py
* feat: Update pytorch (#305)
* (DS-1585) feat(endpoint): added model config with raw retrieval (#308)
* added model config with raw retrieval
* added model description
* feat: retrieve 1000 offers
* resolved gpt comments
---------
=> MEP v20240424 (#309)

apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py
=> (BSR-1707) feat(reco): allows to query similar_offer with category

apps/fraud/compliance/api/dev-requirements.txt, apps/fraud/compliance/api/requirements.in, apps/fraud/compliance/api/requirements.txt, apps/recommendation/README.md, apps/recommendation/api/src/huggy/core/endpoint/retrieval_endpoint.py, apps/recommendation/api/src/huggy/core/model_selection/__init__.py, apps/recommendation/api/src/huggy/core/model_selection/endpoint/user_retrieval.py, apps/recommendation/api/src/huggy/core/model_selection/model_configuration/recommendation.py, apps/recommendation/api/src/huggy/schemas/model_selection/model_configuration.py, apps/recommendation/api/src/huggy/utils/env_vars.py
=> MES v20250522

apps/fraud/compliance/api/src/pcpapillon/views/compliance.py
…ce prediction to prevent crashs (#337)
version:
=> MES v07082025

apps/fraud/compliance/api/src/pcpapillon/utils_llm/data_model_llm.py, apps/fraud/compliance/api/src/pcpapillon/views/compliance.py
=> MEP v07082025

.gitignore, .pre-commit-config.yaml, README.md, linter-requirements.in, linter-requirements.txt
This PR adds the feature ggshield.
=> (DE-2349) feat(ggshield): add ggshield on api-data

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json, apps/recommendation/api/postman/backend/dev_backend.postman_environment.json, apps/recommendation/api/postman/backend/production_backend.postman_environment.json, apps/recommendation/api/postman/backend/staging_backend.postman_environment.json
=> (BSR) fix(integration): Fix reco integration tests

apps/recommendation/api/postman/backend/api_integration_tests_backend.postman_collection.json, apps/recommendation/api/postman/backend/dev_backend.postman_environment.json, apps/recommendation/api/postman/backend/production_backend.postman_environment.json, apps/recommendation/api/postman/backend/staging_backend.postman_environment.json
=> MES v01092025.1
